services:
  backend:
    build: ./backend
    container_name: apagones_backend
    restart: unless-stopped
    environment:
      TURNSTILE_ENABLED: "${TURNSTILE_ENABLED:-0}"
      TURNSTILE_SECRET_KEY: "${TURNSTILE_SECRET_KEY:-}"
    volumes:
      - ./data:/data

  web:
    build: ./frontend
    container_name: apagones_web
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8098:80"
